/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_main_JNITest */

#ifndef _Included_com_main_JNITest
#define _Included_com_main_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_main_JNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_main_JNITest_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
