/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_main_JNIOpencv */

#ifndef _Included_com_main_JNIOpencv
#define _Included_com_main_JNIOpencv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_main_JNIOpencv
 * Method:    detectFace
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_main_JNIOpencv_detectFace
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
